env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "dSuM+3RYoesuXyEt0oAGl/RD8PQQux8kVzWfjYxJMq8FoI1NuHKxHAWW5uCMoZhCya/VGxvA6wysF8gHIeMBuL5KJuA3u9TnnwFUMShfAwN35XGAAGLjHeIM4o2LiRk6FRfLb78PG8UyN/r3YRcgYYXYIJ/88UuaMJQIUAL/JZw="

sudo: required
dist: trusty
language: cpp
compiler: gcc
git:
    depth: 1
before_script:
    - sudo apt-get install ca-certificates
    - cd projects
    - ./genie_linux --gcc=linux-gcc-5 gmake
    - cd tmp/gcc5
    - g++-5 --version
    - g++ --version
script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make verbose=1 config=debug64 ; fi
   
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - ca-certificates

env: COMPILER=g++-5    
